# name: CD Pipeline
# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     name: Deploy Application
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
      
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
      
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: |
#             ${{ secrets.DOCKER_USERNAME }}/fastapi-book-app:latest
#             ${{ secrets.DOCKER_USERNAME }}/fastapi-book-app:${{ github.sha }}
            
#       - name: Deploy to Server
#         uses: appleboy/ssh-action@v1.2.0
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-book-app:latest
#             sudo docker-compose down
#             sudo docker-compose up -
name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fastapi-book-app:latest
            ${{ secrets.DOCKER_USERNAME }}/fastapi-book-app:${{ github.sha }}

      - name: Copy docker-compose.yml to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/fastapi-book-project"  # Adjust this path

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/fastapi-book-project
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-book-app:latest
            sudo docker compose down || docker-compose down
            sudo docker compose up -d --pull always || docker-compose up -d --pull always